### ISSUE TITLE
Error when executing moblizer.py

### ISSUE THREAD

**Issue by aankitgiri** [SudhanshuC/Android-Testing#2]
Hi,

I am getting an error IOError: [Errno 2] No such file or directory: './diva-bet/AndroidManifest.xml'

When executing the moblizer.py, it asked for apk filename. It proceeds and starts using apktool and other stuff. But it encounters an error when it reads the Manifest file.

Any help!

**Comment by besimaltnok** [comment]
Solution : rootpath = b.split(".")[0]

**Comment by talk2noob** [comment]
Facing same issue, Please help.

Test started for diva-beta.apk
Traceback (most recent call last):
  File "C:\Users\username\Downloads\moblizer.py", line 47, in <module>
    call(['apktool','d',b])
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
